#!/usr/bin/env node
// Quotes are fetched by CI, not by the browser.
//
// The reason is technical and there is no way around it from the client: the
// provider that has the historical closes **does not send CORS headers**, so a
// fetch from the page is blocked by the browser. The CORS-open alternatives for
// equities want an API key, and a key inside a static bundle is a public key.
//
// So: this script runs in the runner, reads the symbol from a secret, and
// writes two files that end up in the deployment. The page reads them from its
// own origin — no CORS, no key in the bundle, no third-party request while
// anyone is browsing.
//
// The symbol appears nowhere in the sources and nowhere in the output: it comes
// in from the environment, stays in the runner, and the files it writes contain
// only numbers.
//
//   QUOTE_SYMBOL=... node scripts/fetch-quote.mjs [--history] [--soft]
//
//   --history  add the plan dates that have now passed to the history file
//   --soft     do not fail if the network is down: leave the files as they are

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const QUOTE = path.join(ROOT, "public", "quote.json");
const HISTORY = path.join(ROOT, "src", "data", "reference-prices.json");

const argv = new Set(process.argv.slice(2));
const WITH_HISTORY = argv.has("--history");
const SOFT = argv.has("--soft");

const SYMBOL = process.env.QUOTE_SYMBOL;
// The exchange rate identifies no company, so it can stay in the clear.
const FX_SYMBOL = process.env.FX_SYMBOL ?? "EURUSD=X";

function die(message) {
  // Never print the symbol: this log is public on a public repository.
  console.error(`fetch-quote: ${message}`);
  process.exit(SOFT ? 0 : 1);
}

if (!SYMBOL) die("QUOTE_SYMBOL is missing from the environment (set it as a GitHub secret)");

/** Daily closes for a symbol, over a range. */
async function closes(symbol, fromSec, toSec) {
  const url =
    `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}` +
    `?interval=1d&period1=${fromSec}&period2=${toSec}`;
  const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" } });
  if (!res.ok) throw new Error(`the provider answered ${res.status}`);
  const j = await res.json();
  const r = j?.chart?.result?.[0];
  const stamps = r?.timestamp ?? [];
  const close = r?.indicators?.quote?.[0]?.close ?? [];
  const out = [];
  stamps.forEach((t, i) => {
    const c = close[i];
    if (typeof c === "number" && Number.isFinite(c)) {
      out.push({ date: new Date(t * 1000).toISOString().slice(0, 10), close: c });
    }
  });
  if (!out.length) throw new Error("the provider returned no closes at all");
  return out;
}

const round = (v, d) => Number(v.toFixed(d));
const at = (series, date) => {
  const before = series.filter((x) => x.date <= date);
  return before.length ? before[before.length - 1] : null;
};

const today = new Date().toISOString().slice(0, 10);
// Eleven years back: covers the whole plan history and fits in one request.
const FROM = Math.floor(Date.UTC(new Date().getUTCFullYear() - 11, 0, 1) / 1000);
const TO = Math.floor(Date.now() / 1000) + 86400;

let equity, fx;
try {
  [equity, fx] = await Promise.all([closes(SYMBOL, FROM, TO), closes(FX_SYMBOL, FROM, TO)]);
} catch (e) {
  die(`quotes unavailable: ${e.message}`);
}

// ------------------------------------------------------------------ quote.json

const last = equity[equity.length - 1];
const lastFx = fx[fx.length - 1];
const previous = fs.existsSync(QUOTE) ? JSON.parse(fs.readFileSync(QUOTE, "utf8")) : {};

const nextQuote = {
  $comment:
    previous.$comment ??
    "Generated by scripts/fetch-quote.mjs in CI. The symbol comes from a GitHub secret and does not appear here.",
  date: last.date,
  close: round(last.close, 4),
  eurusd: round(lastFx.close, 6),
  eurusdOn: lastFx.date,
  currency: "USD",
  generatedAt: new Date().toISOString(),
  // A close from three days ago is not an error (at a weekend it is the norm),
  // but more than a week means something upstream has broken.
  stale: (Date.parse(today) - Date.parse(last.date)) / 86400000 > 7,
};

fs.writeFileSync(QUOTE, `${JSON.stringify(nextQuote, null, 2)}\n`);
console.log(`fetch-quote: quote.json updated to the close of ${last.date}`);

// --------------------------------------------------------------- history

if (WITH_HISTORY) {
  const file = JSON.parse(fs.readFileSync(HISTORY, "utf8"));
  const keyDates = file.keyDates;
  const present = new Set(file.prices.map((p) => p.date));
  const years = new Set(file.prices.map((p) => Number(p.date.slice(0, 4))));
  years.add(new Date().getUTCFullYear());

  const added = [];
  for (const year of [...years].sort()) {
    for (const md of keyDates) {
      const date = `${year}-${md}`;
      // Only plan dates that have already passed: a future date has no close,
      // and writing it with the latest available one would be a made-up number.
      if (date > today || present.has(date)) continue;
      const e = at(equity, date);
      const f = at(fx, date);
      if (!e || !f) continue;
      added.push({
        date,
        close: round(e.close, 4),
        closeOn: e.date,
        eurusd: round(f.close, 6),
        eurusdOn: f.date,
      });
    }
  }

  if (added.length) {
    file.prices = [...file.prices, ...added].sort((x, y) => x.date.localeCompare(y.date));
    file.updated = today;
    fs.writeFileSync(HISTORY, `${JSON.stringify(file, null, 2)}\n`);
    console.log(`fetch-quote: ${added.length} plan dates added to the history`);
  } else {
    console.log("fetch-quote: no new dates to add to the history");
  }
}
